### ISSUE TITLE
BUG :: json-schema not rebuilding

### ISSUE THREAD

**Issue by gdbrown** [gdbots/schemas#10]
`composer pbjc` runs without error but the json-schema files are not generated into `./gh-pages/`

**Comment by excelwebzone** [comment]
Correct, by default compiler will use php (see CompileCommand):

``` php
$language = $input->getOption('language') ?: 'php';
```

which is why it doesn't generates json-schemas. You can create another composer script:

``` json
    "pbjc-json-schema": "vendor/bin/pbjc -l json-schema",
```

that will generate json files.

> Note: composer doesn't support passing arguments to command.

**Comment by gdbrown** [comment]
odd, i thought when we introduced the pbjc.yml that it would just run whatever was defined in there.  10 4.

**Comment by excelwebzone** [comment]
Do you want me to make it? I can modify the command to run on all languages?

**Comment by gdbrown** [comment]
if it's quick sure.  it should function like so:
- if config used, process all languages in config.
- if lang option provided (only one at a time)... run only that language and get options from yml if present.

**Comment by excelwebzone** [comment]
Ok, created a ticket https://github.com/gdbots/pbjc-php/issues/17
